extends Node
## Typed-by-contract global facts. Commands remain direct service calls.

signal run_started(run_id: String, seed: int)
signal floor_generated(floor_index: int, manifest: Dictionary)
signal run_ended(summary: Dictionary)
signal permadeath_resolved(summary: Dictionary)
signal hub_entered(meta_snapshot: Dictionary)
signal action_committed(receipt: Dictionary)
signal damage_resolved(receipt: Dictionary)
signal actor_defeated(actor_id: StringName, source_id: StringName)
signal item_acquired(item_id: StringName, amount: int)
signal item_equipped(item_id: StringName, slot: int)
signal story_beat_placed(beat_id: StringName, room_rect: Rect2i)
signal story_beat_triggered(beat_id: StringName)
signal story_flag_changed(flag_id: StringName, value: Variant)
signal dialogue_started(dialogue_id: StringName)
signal dialogue_updated(view_model: Dictionary)
signal dialogue_ended(dialogue_id: StringName)
signal quest_stage_changed(quest_id: StringName, stage_id: StringName)
signal lore_discovered(lore_id: StringName)
signal echo_essence_changed(total: int, delta: int)
signal message_enqueued(channel: StringName, text_key: StringName, parameters: Dictionary)
signal overlay_requested(overlay_id: StringName, payload: Dictionary)
signal save_succeeded(slot: StringName)
signal save_failed(slot: StringName, reason: String)
